version: '3.9'
services:
  nids-api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: nids-api
    env_file:
      - ../.env
    environment:
      - LOG_LEVEL=INFO
      - MODEL_ARTIFACT_DIR=/app/experiments/latest
    ports:
      - "8000:8000"
    restart: unless-stopped
